GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/628cd88264d57586407fa7f9

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "subscribed": true
}

###

POST http://localhost:5000/api/users/add
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "subscribed": true
}

###

PUT http://localhost:5000/api/users
Content-Type: application/json

{
    "_id": "628e564971db5e6396993511",
   "subscribed": false
}