GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/628cd88264d57586407fa7f9

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "aaaa@example.com",
    "password": "hej"
}

###

POST http://localhost:5000/api/users/add
Content-Type: application/json

{
    "username": "blabla",
    "password": "hej",
    "subscribed": true,
    "isLoggedIn": true
}

###

PUT http://localhost:5000/api/users
Content-Type: application/json

{
    "_id": "628e564971db5e6396993511",
   "subscribed": false
}

###

# DELETE http://localhost:5000/api/users/62868138357d7bc6956fc063

# ###